Repository project-alkemi/alkemi-protocol, pull requests merged in 2019-12, with the labels that each got.

#3 Contracts documentation templates
  .solidoc/templates/contract.md
  .solidoc/templates/function.md
  .solidoc/templates/modifier.md
  .solidoc/templates/table-header.md
Labels: documentation, enhancement

#7 CD-143 Automate generating documentation
  .travis.yml
Labels: WIP, documentation

#10 CD-143 Automate generating documentation
  .travis.yml
Labels: documentation

#12 CD-138 Add screenshots to readme
  README.md
  docs/assets/alk-compile.gif
  docs/assets/liquidity-dashboard.gif
Labels: documentation
